version = 0.1
[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "staging-app01"
s3_bucket = "aws-sam-cli-managed-dev"
s3_prefix = "staging-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"stag\""

[production]
[production.deploy]
[production.deploy.parameters]
stack_name = "production-app01"
s3_bucket = "aws-sam-cli-managed-prod"
s3_prefix = "production-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Env=\"prod\""