# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html

# The AWSTemplateFormatVersion identifies the capabilities of the template
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/format-version-structure.html
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: >-
  sam-app


Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  VerifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/lambda_verify
      Handler: index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - "lambda:InvokeFunction"
              - "lambda:ListFunctions"
            Resource: '*'
      Events:
        CommandReceiver:
          Type: Api
          Properties:
            Path: /command
            Method: post
  HandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/lambda_handler
      Handler: lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
