version: '2.1'
orbs:
  sam: circleci/aws-sam-serverless@3.0
jobs:
  test_my_api:
    docker:
      - image: python:3.9
    steps:
      - run:
          name: Run tests
          command: |
            pip install virtualenv
            virtualenv .venv
            source .venv/bin/activate
            pip install -r requirements.txt
            pytest tests
workflows:
  test_and_deploy:
    jobs:
      - sam/deploy:
          name: deploy-staging
          s3-bucket: aws-sam-cli-managed-dev
          stack-name: staging-stack
          template: template.yaml
      - test_my_api:
          requires:
            - deploy-staging
      - sam/deploy:
          name: deploy-production
          requires:
            - test_my_api
          stack-name: production-stack
          template: template.yaml
          s3-bucket: aws-sam-cli-managed-prod
          filters:
            branches:
              only:
               - main
